<div class="appui-vcs-project bbn-overlay">
  <bbn-router :nav="true"
              :master="true"
              orientation="left"
              ref="router"
              class="appui-vcs-project-router">
    <bbns-container url="info"
                    :static="true"
                    :load="false"
                    :title="_('Information')"
                    icon="nf nf-fa-info"
                    component="appui-vcs-project-info"
                    :source="source"/>
    <bbns-container url="branches"
                    :static="true"
                    :load="false"
                    :title="_('Branches')"
                    icon="nf nf-pl-branch"
                    component="appui-vcs-project-branches"
                    :source="source"/>
    <bbns-container url="users"
                    :static="true"
                    :load="false"
                    :title="_('Users')"
                    icon="nf nf-fa-users"
                    component="appui-vcs-project-users"
                    :source="source"/>
  </bbn-router>
</div>